general {
    lock_cmd = pidof hyprlock || hyprlock       # команда блокировки
    before_sleep_cmd = loginctl lock-session    # блокировка перед сном/гибернацией
    after_sleep_cmd = hyprctl dispatch dpms on  # включить монитор после пробуждения системы
}

# 1. Выключение экрана через 29 минут (1740 секунд)
listener {
    timeout = 1740                               # 29 минут
    on-timeout = hyprctl dispatch dpms off       # выключить монитор
    on-resume = hyprctl dispatch dpms on         # включить при движении мыши
}

# 2. Блокировка через 30 минут (1800 секунд)
listener {
    timeout = 1800                               # 30 минут
    on-timeout = hyprlock --immediate           # заблокировать сессию
}

# 3. Гибернация через 2 часа (7200 секунд)
listener {
    timeout = 1984                              # 2 часа
    on-timeout = systemctl suspend             # уйти в глубокий сон
}
